---
title: "Closest_Approach_Code"
author: "John Veon"
date: "2022-11-21"
output: html_document
---

##Read in data and packages
```{r}
CAglmer <- read.csv("./ClosestApproachDat.csv", header=T,)
library(ggplot2)
library(ggfortify)
library(MASS)
library(ggthemes) 
library(lme4)
library(lattice)
library(lmerTest)
library(emmeans)
```

##Variables##
```{r}
CAglmer$Site_Num = as.factor(CAglmer$Site_Num)
CAglmer$Phase_Num = as.factor(CAglmer$Phase_Num)
CAglmer$Distance = CAglmer$Distance
```

##Set-up reference levels for Phase_Num in order to determine all pair wise comparisons
```{r}
CAglmer$Phase_Num2 = relevel(CAglmer$Phase_Num, ref = "2")
CAglmer$Phase_Num = relevel(CAglmer$Phase_Num, ref = "1")
```

###GLMMS for Closest Approach
```{r}
##Model
CAmod1<-glmer(Distance ~ Phase_Num + (1 | Site_Num), data=CAglmer, family = Gamma(link = "log"))
summary(CAmod1)
```

```{r}
##Confidence Intervals
confint(CAmod1, method = "Wald")
```


```{r}
##Same model but with reference level set to During Phase
CAmod<-glmer(Distance ~ Phase_Num2 + (1 | Site_Num), data=CAglmer, family = Gamma(link = "log"))
summary(CAmod)
```

```{r}
##Confidence Intervals
confint(CAmod, method = "Wald")
```

###Model Diagnostics
```{r}
###Check Normality of residuals of fitted model after using Gamma
qqmath(resid(CAmod))
```

##Checking model variances###
```{r}
plot(CAmod)
plot(resid(CAmod))
```

```{r}
###Normality of Intercepts
r_int<- lme4::ranef(CAmod)$Site_Num$`(Intercept)`
qqnorm(r_int)
qqline(r_int)
shapiro.test(r_int)
```

```{r}
###Check variances of random effect
CAglmer$ModelResCA <- residuals(CAmod)
CAglmer$ModelAbsResCA <- abs(CAglmer$ModelResCA)
CAglmer$ModelAbsResSqCA <- CAglmer$ModelAbsResCA^2

levenemodCA <- lm(ModelAbsResSqCA ~ Site_Num, data=CAglmer)
anova(levenemodCA)
```


###Develop Figure###
```{r}
emm <- data.frame(emmeans(CAmod1, ~ Phase_Num, type = "response"))
```

```{r}
levels(emm$Phase_Num) <- c("Pre", "During", "Post") 


ClosestApp = ggplot(emm, aes(x= Phase_Num, y=response, fill = Phase_Num))+
  geom_bar(colour = "black", position="dodge", stat="identity", width = 0.4, size = 0.6) + scale_y_continuous(expand = c(0, 0), limits = c(0, 50)) +
  geom_errorbar(aes(ymin=response-SE, ymax = response+SE), width=0.1,size = 0.6, color = "grey0", position = position_dodge(.9)) + 
  ylab("Mean closest approach (m)") + xlab("Phase") +
  scale_fill_manual("legend", values = c("Pre" = "grey85", "During" = "grey40", "Post" = "grey60")) +
  theme_bw() + theme(legend.position = "none", axis.text.x = element_text(size = 16, color = "black", family = "Arial"), axis.text.y = element_text(size = 16, color = "black", family = "Arial"), axis.title.y = element_text(size = 18, family = "Arial"), axis.title.x = element_text(size = 18, family = "Arial"), legend.title = element_text(size = 16, family = "Arial", face = "bold"), legend.text = element_text(size = 16, color = "black", family = "Arial"), panel.background = element_blank(), panel.border = element_blank(), axis.line = element_line(colour = "black"), panel.grid = element_blank())

ClosestApp
```

